### ISSUE TITLE
MLJ models need to predict vectors, not n x 1 vectors

### ISSUE THREAD

**Issue by ablaom** [IQVIA-ML/LightGBM.jl#32] opened 2020-04-08 19:22 UTC
The prediction of any `Deterministic` model ought generally to have the same type as the training target. 

```julia
julia> X, y = @load_boston;

julia> model = LightGBM.MLJInterface.LGBMRegressor();

julia> mach = machine(model, X, y) |> fit!

julia> yhat = predict(mach);

julia> yhat isa AbstractVector # should be true
false

julia> size(yhat)
(506, 1)
```

So for example, this throws an error:

```julia
rms(yhat, y)
```

**Comment by ablaom** [comment] 2020-04-08 20:05
Can I suggest that to catch more such errors you introduce the following to your tests:

```julia
using MLJBase
import LightGBM

X, y = @load_boston;
model = LightGBM.MLJInterface.LGBMRegressor()
evaluate(model, X, y)

X, y = @load_iris;
model = LightGBM.MLJInterface.LGBMClassifier()
evaluate(model, X, y)
```

**Comment by ablaom** [comment] 2020-04-09 00:12
BTW the classifier looks good to go.

**Comment by yalwan-iqvia** [comment] 2020-04-09 06:45
Great thanks, incoming PR soon

**Comment by yalwan-iqvia** [comment] 2020-04-09 07:06
I'm trying to add those statements to tests but I seeing error likethis:

```
  Got exception outside of a @test
  LoadError: IOError: write: broken pipe (EPIPE)
  try_yieldto(::typeof(Base.ensure_rescheduled), ::Base.RefValue{Task}) at ./task.jl:517
  wait() at ./task.jl:592
  uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:883
  unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:931
  macro expansion at ./gcutils.jl:87 [inlined]
  write at ./strings/io.jl:177 [inlined]
  print at ./strings/io.jl:179 [inlined]
  printover(::Base.PipeEndpoint, ::String, ::Symbol) at /home/yalwan/.julia/packages/ProgressMeter/g1lse/src/ProgressMeter.jl:436
  #updateProgress!#9(::Array{Any,1}, ::Symbol, ::Int64, ::Bool, ::typeof(ProgressMeter.updateProgress!), ::ProgressMeter.Progress) at /home/yalwan/.julia/packages/ProgressMeter/g1lse/src/ProgressMeter.jl:220
  lock(::getfield(ProgressMeter, Symbol("##13#14")){Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},ProgressMeter.Progress}, ::Base.Threads.SpinLock) at /home/yalwan/.julia/packages/ProgressMeter/g1lse/src/ProgressMeter.jl:184
  #next!#12 at /home/yalwan/.julia/packages/ProgressMeter/g1lse/src/ProgressMeter.jl:313 [inlined]
  next! at /home/yalwan/.julia/packages/ProgressMeter/g1lse/src/ProgressMeter.jl:313 [inlined]
  macro expansion at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:659 [inlined]
  (::getfield(MLJBase, Symbol("##185#193")){Int64,ProgressMeter.Progress,Distributed.RemoteChannel{Channel{Bool}}})() at ./task.jl:268
  Stacktrace:
   [1] sync_end(::Array{Any,1}) at ./task.jl:235
   [2] macro expansion at ./task.jl:254 [inlined]
   [3] evaluate!(::MLJBase.Machine{LightGBM.MLJInterface.LGBMClassifier}, ::Array{Tuple{Array{Int64,1},UnitRange{Int64}},1}, ::Nothing, ::Nothing, ::Int64, ::Int64, ::Array{MLJBase.CrossEntropy{Float64},1}, ::typeof(MLJModelInterface.predict), ::ComputationalResources.CPU1{Nothing}, ::Bool) at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:656
   [4] evaluate!(::MLJBase.Machine{LightGBM.MLJInterface.LGBMClassifier}, ::MLJBase.CV, ::Nothing, ::Nothing, ::Int64, ::Int64, ::Array{MLJBase.CrossEntropy{Float64},1}, ::Function, ::ComputationalResources.CPU1{Nothing}, ::Bool) at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:726
   [5] #evaluate!#173(::MLJBase.CV, ::Nothing, ::Nothing, ::Nothing, ::Function, ::ComputationalResources.CPU1{Nothing}, ::Nothing, ::Int64, ::Bool, ::Bool, ::Int64, ::typeof(MLJBase.evaluate!), ::MLJBase.Machine{LightGBM.MLJInterface.LGBMClassifier}) at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:521
   [6] evaluate!(::MLJBase.Machine{LightGBM.MLJInterface.LGBMClassifier}) at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:491
   [7] #evaluate#178 at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:539 [inlined]
   [8] evaluate(::LightGBM.MLJInterface.LGBMClassifier, ::NamedTuple{(:sepal_length, :sepal_width, :petal_length, :petal_width),NTuple{4,Array{Float64,1}}}, ::CategoricalArrays.CategoricalArray{String,1,UInt32,String,CategoricalArrays.CategoricalString{UInt32},Union{}}) at /home/yalwan/.julia/packages/MLJBase/uJ1jK/src/resampling.jl:539
   [9] top-level scope at /home/yalwan/git/LightGBM.jl/test/mlj/multiclass_classifier.jl:57
   [10] include at ./boot.jl:328 [inlined]
   [11] include_relative(::Module, ::String) at ./loading.jl:1094
   [12] include(::Module, ::String) at ./Base.jl:31
   [13] include(::String) at ./client.jl:431
   [14] top-level scope at /home/yalwan/git/LightGBM.jl/test/runtests.jl:24
   [15] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [16] top-level scope at /home/yalwan/git/LightGBM.jl/test/runtests.jl:24
   [17] top-level scope at /builddir/build/BUILD/julia/build/usr/share/julia/stdlib/v1.2/Test/src/Test.jl:1113
   [18] top-level scope at /home/yalwan/git/LightGBM.jl/test/runtests.jl:19
   [19] include(::String) at ./client.jl:431
   [20] top-level scope at none:5
  in expression starting at /home/yalwan/git/LightGBM.jl/test/mlj/multiclass_classifier.jl:57
  
```
Not really sure whats up because I could run those commands in the REPL

**Comment by yalwan-iqvia** [comment] 2020-04-09 07:12
In fact this only occurs for classification, regression one with `@load_boston` works fine!

**Comment by yalwan-iqvia** [comment] 2020-04-09 08:09
Ok, further comments:  
I wanted to include this into automated tests but it caused ... unclear ... problems with status checks.
I do think its related to broken pipe error

I couldn't help but notice this:

```
julia> typeof(output)
NamedTuple{(:measure, :measurement, :per_fold, :per_observation),Tuple{Array{MLJBase.RMS,1},Array{Float64,1},Array{Array{Float64,1},1},Array{Missing,1}}}

julia> output = evaluate(model, X, y)
Evaluating over 6 folds: 100%[=========================] Time: 0:00:00
┌───────────┬───────────────┬─────────────────────────────────────┐
│ _.measure │ _.measurement │ _.per_fold                          │
├───────────┼───────────────┼─────────────────────────────────────┤
│ rms       │ 5.91          │ [3.69, 3.87, 6.35, 6.48, 8.7, 4.79] │
└───────────┴───────────────┴─────────────────────────────────────┘
_.per_observation = [missing]


julia> 
```

It does seem to me like theres some strange output trickery going on here which isn't compatible with headless terminals etc, and it's probably likely to be the root cause of why I got weird errors when trying to run this through status checks.

Take for example, this non-descript error which occurred during a MacOS (linux ones passed fine ...) status check

```
ERROR: Package LightGBM errored during testing
Stacktrace:
 [1] pkgerror(::String, ::Vararg{String,N} where N) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Types.jl:113
 [2] #test#131(::Bool, ::Nothing, ::Cmd, ::Cmd, ::typeof(Pkg.Operations.test), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/Operations.jl:1372
 [3] #test at ./none:0 [inlined]
 [4] #test#62(::Bool, ::Nothing, ::Cmd, ::Cmd, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(Pkg.API.test), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:253
 [5] (::Pkg.API.var"#kw##test")(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(Pkg.API.test), ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at ./none:0
 [6] #test#58 at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.3/Pkg/src/API.jl:233 [inlined]
 [7] (::Pkg.API.var"#kw##test")(::NamedTuple{(:coverage,),Tuple{Bool}}, ::typeof(Pkg.API.test)) at ./none:0
 [8] top-level scope at none:1
##[error]Process completed with exit code 1.
```

This happened despite several restarts ...

So for now, I can't include these tests but they are there commented out with the understanding that I want to re-enable them. Unless you can suggest an alternative to the evaluate function which will let me get close functionally but skip the dodgy output formatting.

**Comment by ablaom** [comment] 2020-04-10 00:14
I'm not immediately able to explain the PipeError problem. If this persists and you believe it's an MLJ issue, please post an issue.

Instead, you could do:

```julia
using Test
using MLJBase
import LightGBM

X, y = @load_boston;
model = LightGBM.MLJInterface.LGBMRegressor()
yhat = machine(model, X, y) |> fit! |> predict;
scitype(yhat) == AbstractVector{Continuous}
@test rms(yhat, y) < 6  # or do proper out-of-sample test 

X, y = @load_iris;
model = LightGBM.MLJInterface.LGBMClassifier()
yhat = machine(model, X, y) |> fit! |> predict;
@test scitype(mode.(yhat)) <: AbstractVector{Multiclass{3}}
@test mean(cross_entropy(yhat, y)) < 0.6  # or do proper out-of-sample test 
```

Happy for you to close this issue.

**Comment by yalwan-iqvia** [comment] 2020-04-14 09:15
Original problem is dealt with. Closing

**Closed by yalwan-iqvia** 2020-04-14 09:15 UTC
